services:
  ceo_track:
    container_name: "ceo_track"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ceo_track.db:/app/ceo_track.db
    logging:
      driver: json-file
      options:
        max-size: "32m"
        max-file: "3"
